package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestManpageGeneration_Deterministic proves the volatile-header
// strip works: regenerating the man pages on the same source SHA
// produces byte-identical output. Without that property, every CI
// run would re-touch the files and the drift-guard tests below would
// chase a moving target.
func TestManpageGeneration_Deterministic(t *testing.T) {
	a := t.TempDir()
	b := t.TempDir()
	if err := generate(a); err != nil {
		t.Fatalf("generate a: %v", err)
	}
	if err := generate(b); err != nil {
		t.Fatalf("generate b: %v", err)
	}
	entries, err := os.ReadDir(filepath.Join(a, "man1"))
	if err != nil {
		t.Fatalf("read a: %v", err)
	}
	if len(entries) == 0 {
		t.Fatalf("generate produced no man pages in %s/man1", a)
	}
	for _, e := range entries {
		name := e.Name()
		ra, err := os.ReadFile(filepath.Join(a, "man1", name))
		if err != nil {
			t.Fatalf("read a/%s: %v", name, err)
		}
		rb, err := os.ReadFile(filepath.Join(b, "man1", name))
		if err != nil {
			t.Fatalf("read b/%s: %v", name, err)
		}
		if !bytes.Equal(ra, rb) {
			t.Errorf("man page %s differs across regenerations; volatile-header strip is broken", name)
		}
	}
}

// TestManpageGeneration_StripsCobraDate verifies the .TH header's
// third quoted field — cobra/doc's date — is rewritten to an empty
// string. The roff syntax is positional; this test pins the exact
// shape so a future cobra release that changes the header layout
// fails loudly rather than silently re-introducing the date.
func TestManpageGeneration_StripsCobraDate(t *testing.T) {
	dir := t.TempDir()
	if err := generate(dir); err != nil {
		t.Fatalf("generate: %v", err)
	}
	raw, err := os.ReadFile(filepath.Join(dir, "man1", "distill-ai.1"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	lines := strings.Split(string(raw), "\n")
	var th string
	for _, l := range lines {
		if strings.HasPrefix(l, ".TH ") {
			th = l
			break
		}
	}
	if th == "" {
		t.Fatalf("no .TH header in generated page; got:\n%s", raw)
	}
	// The expected shape after strip is:
	//   .TH "DISTILL-AI" "1" "" "Auto generated by spf13/cobra" ""
	// The third quoted token MUST be empty; the fourth carries
	// the cobra marker and is left alone.
	if !strings.Contains(th, `"DISTILL-AI" "1" ""`) {
		t.Errorf("expected stripped date in .TH header, got: %q", th)
	}
}

// TestManpageGeneration_CoversEverySubcommand asserts that every
// subcommand the cobra tree exposes (run, detect, list-formats,
// explain, completions, version) gets its own man page. The drift
// guard catches the case where a new verb is added without
// regenerating; the man/ directory should be regenerated in the
// same commit that adds the verb.
func TestManpageGeneration_CoversEverySubcommand(t *testing.T) {
	dir := t.TempDir()
	if err := generate(dir); err != nil {
		t.Fatalf("generate: %v", err)
	}
	wanted := []string{
		"distill-ai.1",
		"distill-ai-run.1",
		"distill-ai-detect.1",
		"distill-ai-list-formats.1",
		"distill-ai-explain.1",
		"distill-ai-completions.1",
		"distill-ai-version.1",
	}
	for _, name := range wanted {
		path := filepath.Join(dir, "man1", name)
		if _, err := os.Stat(path); err != nil {
			t.Errorf("expected man page missing: %s", name)
		}
	}
}
